<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="DatabaseManagement\CarStatisticsDatabase.db" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="DatabaseManagement\CarStatisticsDatabase.db">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.9" />
    <PackageReference Include="System.Data.SQLite" Version="2.0.2" />
  </ItemGroup>

</Project>
